### ISSUE TITLE
demo 运行报错

### ISSUE THREAD

**Issue by lvyongtao** [DLTech21/ofd.iOS#1]
Showing All Messages
In /Downloads/ofd.iOS-main/OFDDemo/libOFDParser.a(CairoDraw.o), building for iOS, but linking in object file built for iOS Simulator, file '/Downloads/ofd.iOS-main/OFDDemo/libOFDParser.a' for architecture arm64

**Comment by DLTech21** [comment]
模拟器运行？

**Comment by lvyongtao** [comment]
真机&nbsp;


852261135
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 中午1:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DLTech21/ofd.iOS] demo 运行报错 (Issue #1)





 
模拟器运行？

**Comment by DLTech21** [comment]
你先用模拟器吧

**Comment by DLTech21** [comment]
真机的lib稍后传上去

**Comment by lvyongtao** [comment]
模拟器和真机 都跑不起来&nbsp;


852261135
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 中午1:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DLTech21/ofd.iOS] demo 运行报错 (Issue #1)





 
你先用模拟器吧

**Comment by DLTech21** [comment]
运行环境？

**Comment by lvyongtao** [comment]
Xcode14.3 build失败 错误信息麻烦看issue&nbsp;


852261135
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 中午1:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DLTech21/ofd.iOS] demo 运行报错 (Issue #1)





 
运行环境？

**Comment by DLTech21** [comment]
cpu是m系列？

**Comment by lvyongtao** [comment]
是的&nbsp;


852261135
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 中午1:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DLTech21/ofd.iOS] demo 运行报错 (Issue #1)





 
cpu是m系列？

**Comment by DLTech21** [comment]
暂时没有环境尝试，建议先用intel的环境跑

**Comment by lvyongtao** [comment]
好的 那我用intel的试试&nbsp;


852261135
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 中午1:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DLTech21/ofd.iOS] demo 运行报错 (Issue #1)





 
暂时没有环境尝试，建议先用intel的环境跑

**Comment by lvyongtao** [comment]
麻烦上传下真机运行的包 谢谢




852261135
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DLTech21/ofd.iOS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月3日(星期四) 中午1:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DLTech21/ofd.iOS] demo 运行报错 (Issue #1)





 
暂时没有环境尝试，建议先用intel的环境跑

**Comment by DLTech21** [comment]
已上传

**Comment by lvyongtao** [comment]
麻烦问下 字体文件是必须要传递的参数吗&nbsp;&nbsp;


852261135
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 下午2:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DLTech21/ofd.iOS] demo 运行报错 (Issue #1)





 
已上传

**Comment by lvyongtao** [comment]
预览其他ofd文件 直接闪退

**Comment by DLTech21** [comment]
字体文件必须，iOS怎么有宋体之类的字体；
OFD可以上传上来吗？

**Comment by lvyongtao** [comment]
麻烦加我下qq 852261135 我发你 谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Donal ***@***.***&gt;
发送时间: 2023年8月3日 17:20
收件人: DLTech21/ofd.iOS ***@***.***&gt;
抄送: TaoaiM ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [DLTech21/ofd.iOS] demo 运行报错 (Issue #1)





 
字体文件必须，iOS怎么有宋体之类的字体；
 OFD可以上传上来吗？
